name: procgen
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  # https://www.anaconda.com/utilizing-the-new-compilers-in-anaconda-distribution-5/
  - c-compiler=1.3.0
  - cmake=3.21.3
  - qt=5.15.8
  - filelock
  - numpy
  - gym
  - pip
  - pip:
    - gym3==0.3.3
